import type { Vessel, FaunaSpot, ExpeditionRoute, WeatherData } from '../types';

export const FALLBACK_WEATHER: WeatherData = {
  temperature: 14,
  windSpeed: 12,
  windDirection: 'SO (SudOeste)',
  tideState: 'Pleamar',
  tideHeight: '2.1m',
  moonPhase: 'Gibosa Creciente',
  location: 'Puerto Montt & Canales Australes',
  isFallback: true,
};

export const FLEET_DATA: Vessel[] = [
  {
    id: 'vegvisir',
    name: 'Velero Vegvisir',
    type: 'Velero de Travesía',
    tagline: 'La verdadera autenticidad del viento y la navegación austral',
    description: 'El Vegvisir es un velero diseñado para enfrentar los mares más exigentes de la Patagonia con serenidad, calidez de madera noble y un sistema de calefacción central para un confort térmico absoluto.',
    length: '52 Pies (15.8 metros)',
    capacity: 'Hasta 6 Huéspedes',
    crew: 'Patrón de Ultramar + Co-patrón + Chef de A bordo',
    badge: 'Expedición A Vela',
    features: [
      'Calefacción central hidrónica en camarotes y salón',
      'Casco reforzado para canales australes',
      'Camarotes suites matrimoniales con baño privado',
      'Cocina gourmet adaptada a pesca del día',
      'Zodiac auxiliar con motor silencioso para desembarco',
    ],
    mainImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    hotspots: [
      {
        id: 'veg-1',
        title: 'Camarote Suite Principal',
        description: 'Cama Queen de confort superior con vista hacia la cubierta y aislamiento térmico acústico.',
        coordinates: { x: -0.8, y: 0.2, z: 0.5 },
        category: 'Camarote',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'veg-2',
        title: 'Salón Panorámico & Bitácora',
        description: 'Comedor central de caoba con calefacción radiante e instrumental náutico de precisión.',
        coordinates: { x: 0, y: 0.4, z: 0 },
        category: 'Cubierta',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'veg-3',
        title: 'Puente de Mando & Rueda de Timón',
        description: 'Puesto de pilotaje exterior protegido con visión 360° de ventisqueros y cumbres.',
        coordinates: { x: 1.2, y: 0.6, z: -0.2 },
        category: 'Puente de Mando',
        image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'terranova',
    name: 'Yate Terranova',
    type: 'Yate Motor Panorámico',
    tagline: 'Velocidad, salones panorámicos y vistas 360° entre glaciares',
    description: 'El Terranova representa el equilibrio perfecto entre autonomía de navegación y lujo contemporáneo. Sus amplios ventanales de piso a techo permiten contempla glaciares desembarcando con total distinción.',
    length: '68 Pies (20.7 metros)',
    capacity: 'Hasta 8 Huéspedes',
    crew: 'Capitán + 2 Tripulantes + Chef Concierge',
    badge: 'Motor de Ultralujo',
    features: [
      'Flybridge elevado con jacuzzi exterior termo-regulado',
      'Salón principal con ventanales panópticos de 360°',
      'Estabilizadores de navegación de última generación',
      'Plataforma de baño hidráulica para kayaks y paddleboards',
      'Bodega de vinos climatizada y cava privada',
    ],
    mainImage: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80',
    hotspots: [
      {
        id: 'ter-1',
        title: 'Flybridge & Jacuzzi Vista Glaciar',
        description: 'Terraza superior elevada para observar los ventisqueros con trago de autor en mano.',
        coordinates: { x: 0.2, y: 1.1, z: 0 },
        category: 'Cubierta',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ter-2',
        title: 'Master Stateroom',
        description: 'Suite a toda manga con cama King, baño de mármol y ventanales al nivel del agua.',
        coordinates: { x: -1.0, y: -0.2, z: 0 },
        category: 'Camarote',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ter-3',
        title: 'Cava Gourmet & Lounge Principal',
        description: 'Espacio de estar con acabados en nogal, sistema de audio alta fidelidad y cava de autor.',
        coordinates: { x: 0.5, y: 0.3, z: 0.4 },
        category: 'Gastronomía',
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
];

export const FAUNA_CALENDAR: FaunaSpot[] = [
  {
    id: 'ballenas-jorobadas',
    name: 'Ballena Jorobada & Azul',
    scientificName: 'Megaptera novaeangliae',
    months: [11, 12, 1, 2, 3, 4],
    locationName: 'Parque Marino Tantauco & Golfo del Corcovado',
    coordinatesName: '43°12\'S 73°45\'W',
    description: 'Avistamiento privilegiado de cetáceos alimentándose en los canales australes ricos en krill.',
    image: 'https://images.unsplash.com/photo-1568430460464-02e0b9b3e648?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Mañana (08:00 - 12:00 hrs)',
  },
  {
    id: 'orcas-patagonicas',
    name: 'Orcas de los Fiordos',
    scientificName: 'Orcinus orca',
    months: [12, 1, 2, 3],
    locationName: 'Canal Puyuhuapi & Fiordo de Aysén',
    coordinatesName: '44°35\'S 72°40\'W',
    description: 'Grupos familiares de orcas patagónicas patrullando de manera silenciosa entre las montañas sumergidas.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Atardecer (16:00 - 19:30 hrs)',
  },
  {
    id: 'delfin-austral',
    name: 'Delfín Austral & Tonina',
    scientificName: 'Lagenorhynchus australis',
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    locationName: 'Seno de Reloncaví & Archipiélago de Chiloé',
    coordinatesName: '41°40\'S 72°50\'W',
    description: 'Delfines juguetones que acompañan la proa del velero Vegvisir durante la navegación a vela.',
    image: 'https://images.unsplash.com/photo-1570481662006-a3a1374699e8?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Todo el día durante navegación',
  },
  {
    id: 'pingueinera-magallanica',
    name: 'Pingüino de Magallanes y Humboldt',
    scientificName: 'Spheniscus magellanicus',
    months: [10, 11, 12, 1, 2, 3],
    locationName: 'Islotes de Puñihuil & Seno Otway',
    coordinatesName: '41°55\'S 74°02\'W',
    description: 'Colonialismo nidificante donde conviven ambas especies de pingüinos en santuarios protegidos.',
    image: 'https://images.unsplash.com/photo-1598439210625-5067c578f3f6?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Mediodía (11:00 - 15:00 hrs)',
  },
  {
    id: 'termas-nevadas',
    name: 'Cumbres Nevadas & Termas Naturales',
    scientificName: 'Paisaje & Bienestar',
    months: [5, 6, 7, 8, 9, 10],
    locationName: 'Termas de Puyuhuapi & Fiordo Comau',
    coordinatesName: '42°20\'S 72°30\'W',
    description: 'Baños térmicos al aire libre rodeados de nieve y bosque templado lluvioso en completa soledad.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Tarde / Noche estrellada',
  },
];

export const EXPEDITION_ROUTES: ExpeditionRoute[] = [
  {
    id: 'ruta-fiordos-glaciares',
    title: 'Ruta 1: Fiordos Secretos & Glaciares Milenarios',
    subtitle: 'Puerto Montt — Chiloé — Ventisquero Pío XI',
    duration: '7 Días / 6 Noches',
    highlights: ['Navegación entre glaciares de pared', 'Aguas termales en Fiordo Comau', 'Gastronomía de autor con mariscos locales', 'Avistamiento de Toninas Overas'],
    description: 'Una travesía inolvidable ingresando por fiordos inexplorados donde las paredes de roca caen directo al mar turquesa.',
    mapImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir o Yate Terranova',
  },
  {
    id: 'ruta-cabo-hornos',
    title: 'Ruta 2: Expedición Cabo de Hornos Exclusiva',
    subtitle: 'Puerto Williams — Canal Beagle — Isla de Hornos',
    duration: '10 Días / 9 Noches',
    highlights: ['Bautizo de navegación en el mítico Cabo de Hornos', 'Fotografía de naturaleza con Guy Wenborne', 'Parque Nacional Yendegaia', 'Cupos limitados a 5 huéspedes'],
    description: 'La cima de la aventura náutica mundial: circunvalar el extremo sur de América en condiciones de máxima seguridad y lujo.',
    mapImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir (Patrón de Ultramar)',
  },
  {
    id: 'ruta-juan-fernandez',
    title: 'Ruta 3: Archipiélago Juan Fernández & Isla Selkirk',
    subtitle: 'Navegación Oceánica — Robinson Crusoe — Alejandro Selkirk',
    duration: '12 Días / 11 Noches',
    highlights: ['Trekking en la mítica isla Robinson Crusoe', 'Buceo en aguas endémicas cristalinas', 'Estadía combinada en Lodge Rincón de Navegantes', 'Lobos marinos de dos pelos'],
    description: 'La expedición insular por excelencia hacia uno de los ecosistemas con mayor endemismo del planeta.',
    mapImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Yate Terranova & Lodge Rincón de Navegantes',
  },
];
