import type { Vessel, FaunaSpot, ExpeditionRoute, WeatherData } from '../types';

export const FALLBACK_WEATHER: WeatherData = {
  temperature: 14,
  windSpeed: 12,
  windDirection: 'SO (SudOeste)',
  tideState: 'Pleamar',
  tideHeight: '2.1m',
  moonPhase: 'Gibosa Creciente',
  location: 'Puerto Montt & Canales Australes',
  isFallback: true,
};

export const FLEET_DATA: Vessel[] = [
  {
    id: 'vegvisir',
    name: 'Velero Vegvisir',
    type: 'Velero de Expedición',
    tagline: 'Dufour 52.5 ft francés de expedición austral con Starlink 24/7 y autonomía total',
    description: 'El Vegvisir es un velero de expedición Dufour 52.5 ft de astillero francés (Matrícula QUI 2718), diseñado para navegar las aguas australes y el Cabo de Hornos con total serenidad. Dispone de capacidad para 12 pax distribuidos en 5 cabinas con 5 baños, amplio salón central, cocina completa, desalinizador de 140 ltrs/hr, conexión satelital Starlink 24/7, instrumental Raymarine y Zodiac de desembarco con motor Mercury.',
    length: '52.5 Pies (16 metros)',
    capacity: 'Capacidad 12 pax',
    cabins: '5 Cabinas',
    bathrooms: '5 Baños',
    registration: 'QUI 2718',
    builder: 'Dufour (Francés)',
    crew: 'Patrón de Ultramar + Co-patrón + Tripulación / Chef',
    badge: 'Dufour 52.5 ft • Matrícula QUI 2718',
    features: [
      'Astillero Francés Dufour 52.5 ft • Matrícula QUI 2718',
      'Capacidad 12 pax • 5 Cabinas privadas y 5 Baños',
      'Amplio salón central y cocina completa equipada',
      'Conexión satelital Starlink 24/7 en toda la travesía',
      'Plotter y Piloto Automático Raymarine de alta precisión',
      'Desalinizador 140 ltrs/hr con autonomía de agua dulce',
      'Zodiac desembarco 4.3 mts con motor Mercury 4T de 15 hp',
    ],
    mainImage: '/travesia-robinson.jpg',
    hotspots: [
      {
        id: 'veg-1',
        title: 'Cabinas & Baños Privados (5 Cabinas / 5 Baños)',
        description: 'Capacidad para 12 pasajeros distribuidos en 5 cabinas independientes con 5 baños y climatización.',
        coordinates: { x: -0.8, y: 0.2, z: 0.5 },
        category: 'Camarote',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'veg-2',
        title: 'Amplio Salón Central & Cocina Completa',
        description: 'Espacio social panorámico con cocina completa equipada, mesa de navegación y Starlink 24/7.',
        coordinates: { x: 0, y: 0.4, z: 0 },
        category: 'Cubierta',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'veg-3',
        title: 'Puesto de Mando Raymarine & Zodiac 4.3m',
        description: 'Plotter y Piloto Automático Raymarine, junto a Zodiac 4.3m con motor Mercury 4T 15hp para desembarcos.',
        coordinates: { x: 1.2, y: 0.6, z: -0.2 },
        category: 'Puente de Mando',
        image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'terranova',
    name: 'Yate Terranova',
    type: 'Yate de Expedición',
    tagline: 'Hatteras 65ft LRC americano de 3 cubiertas, 20 pax, 3.000 MN de autonomía y Starlink 24/7',
    description: 'El Terranova es un yate de expedición oceánica Hatteras 65ft LRC de astillero americano (Matrícula PMO 6128). Diseñado con 3 cubiertas completas, capacidad para 20 pax, 5 cabinas con 5 baños, doble puente de gobierno (Raymarine + Garmin), 2 motores Detroit 450hp (10.000L de estanque, 3.000 MN de autonomía a 10 kts), 2 generadores Northern Lights 10kVA, 2 desalinizadores de 140 ltrs/hr, Starlink 24/7 y Zodiac semirrígido con motor Yamaha 70hp y grúa de 1 tonelada.',
    length: '65 Pies LRC (20 metros)',
    capacity: 'Capacidad 20 pax',
    cabins: '5 Cabinas (Cubierta 1)',
    bathrooms: '5 Baños',
    registration: 'PMO 6128',
    builder: 'Hatteras 65ft LRC (Americano)',
    crew: 'Capitán + Tripulación / Chef',
    badge: 'Hatteras 65ft LRC • Matrícula PMO 6128',
    features: [
      'Astillero Americano Hatteras 65ft LRC • Matrícula PMO 6128',
      'Capacidad 20 pax • 3 Cubiertas completas (5 Cabinas / 5 Baños)',
      'Cubierta 2: Puente de gobierno, Deck central, Comedor, Cocina full y Popa',
      'Cubierta 3: 2do Puente de gobierno, Deck superior, Parrilla y Grúa 1 ton',
      '2 Motores Detroit 450hp c/u • Estanque 10.000L • 3.000 MN autonomía (10 kts)',
      'Plotter y Piloto Automático doble (Raymarine + Garmin)',
      'Conexión Satelital Starlink 24/7 y 2 Generadores Northern Lights 10kVA',
      '2 Desalinizadores 140 ltrs/hr y Zodiac semirrígido Yamaha 4T 70hp',
    ],
    mainImage: '/zarpe-archipielago.jpg',
    hotspots: [
      {
        id: 'ter-1',
        title: 'Cubierta 1: 5 Cabinas & 5 Baños Privados (20 PAX)',
        description: 'Cubierta de dormitorios con 5 cabinas independientes y 5 baños privados para hasta 20 pasajeros.',
        coordinates: { x: -1.0, y: -0.2, z: 0 },
        category: 'Camarote',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ter-2',
        title: 'Cubierta 2: Puente Principal, Salón, Comedor & Cocina Full',
        description: 'Deck central con puente de gobierno, amplio comedor, cocina full equipo y terraza de popa.',
        coordinates: { x: 0.5, y: 0.3, z: 0.4 },
        category: 'Gastronomía',
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ter-3',
        title: 'Cubierta 3: 2do Puente, Deck Superior, Parrilla, Grúa 1T & Zodiac 70hp',
        description: 'Flybridge con 2do puesto de gobierno, parrilla, grúa de 1 tonelada y Zodiac semirrígido Yamaha 70hp.',
        coordinates: { x: 0.2, y: 1.1, z: 0 },
        category: 'Cubierta',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
];

export const FAUNA_CALENDAR: FaunaSpot[] = [
  {
    id: 'ballenas-jorobadas',
    name: 'Ballena Jorobada & Azul',
    scientificName: 'Megaptera novaeangliae',
    months: [11, 12, 1, 2, 3, 4],
    locationName: 'Parque Marino Tantauco & Golfo del Corcovado',
    coordinatesName: '43°12\'S 73°45\'W',
    description: 'Avistamiento privilegiado de cetáceos alimentándose en los canales australes ricos en krill.',
    image: 'https://images.unsplash.com/photo-1568430460464-02e0b9b3e648?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Mañana (08:00 - 12:00 hrs)',
  },
  {
    id: 'orcas-patagonicas',
    name: 'Orcas de los Fiordos',
    scientificName: 'Orcinus orca',
    months: [12, 1, 2, 3],
    locationName: 'Canal Puyuhuapi & Fiordo de Aysén',
    coordinatesName: '44°35\'S 72°40\'W',
    description: 'Grupos familiares de orcas australes patrullando de manera silenciosa entre las montañas sumergidas.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Atardecer (16:00 - 19:30 hrs)',
  },
  {
    id: 'delfin-austral',
    name: 'Delfín Austral & Tonina',
    scientificName: 'Lagenorhynchus australis',
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    locationName: 'Seno de Reloncaví & Archipiélago de Chiloé',
    coordinatesName: '41°40\'S 72°50\'W',
    description: 'Delfines juguetones que acompañan la proa del velero Vegvisir durante la navegación a vela.',
    image: 'https://images.unsplash.com/photo-1570481662006-a3a1374699e8?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Todo el día durante navegación',
  },
  {
    id: 'pingueinera-magallanica',
    name: 'Pingüino de Magallanes y Humboldt',
    scientificName: 'Spheniscus magellanicus',
    months: [10, 11, 12, 1, 2, 3],
    locationName: 'Islotes de Puñihuil & Seno Otway',
    coordinatesName: '41°55\'S 74°02\'W',
    description: 'Colonialismo nidificante donde conviven ambas especies de pingüinos en santuarios protegidos.',
    image: 'https://images.unsplash.com/photo-1598439210625-5067c578f3f6?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Mediodía (11:00 - 15:00 hrs)',
  },
  {
    id: 'termas-nevadas',
    name: 'Cumbres Nevadas & Termas Naturales',
    scientificName: 'Paisaje & Bienestar',
    months: [5, 6, 7, 8, 9, 10],
    locationName: 'Termas de Puyuhuapi & Fiordo Comau',
    coordinatesName: '42°20\'S 72°30\'W',
    description: 'Baños térmicos al aire libre rodeados de nieve y bosque templado lluvioso en completa soledad.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    bestViewTime: 'Tarde / Noche estrellada',
  },
];

export const EXPEDITION_ROUTES: ExpeditionRoute[] = [
  {
    id: 'ruta-fiordos-glaciares',
    title: 'Ruta 1: Fiordos Secretos & Glaciares Milenarios',
    subtitle: 'Puerto Montt — Chiloé — Ventisquero Pío XI',
    duration: '7 Días / 6 Noches',
    highlights: ['Navegación entre glaciares de pared', 'Aguas termales en Fiordo Comau', 'Gastronomía de autor con mariscos locales', 'Avistamiento de Toninas Overas'],
    description: 'Una travesía inolvidable ingresando por fiordos inexplorados donde las paredes de roca caen directo al mar turquesa.',
    mapImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir o Yate Terranova',
  },
  {
    id: 'ruta-cabo-hornos',
    title: 'Ruta 2: Expedición Cabo de Hornos Exclusiva',
    subtitle: 'Puerto Williams — Canal Beagle — Isla de Hornos',
    duration: '10 Días / 9 Noches',
    highlights: ['Bautizo de navegación en el mítico Cabo de Hornos', 'Fotografía de naturaleza con Guy Wenborne', 'Parque Nacional Yendegaia', 'Cupos limitados a 5 huéspedes'],
    description: 'La cima de la aventura náutica mundial: circunvalar el extremo sur de América en condiciones de máxima seguridad y lujo.',
    mapImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir (Patrón de Ultramar)',
  },
  {
    id: 'ruta-juan-fernandez',
    title: 'Ruta 3: Isla Robinson Crusoe & Cumberland',
    subtitle: 'Navegación Oceánica — Robinson Crusoe — Bahía Cumberland',
    duration: '8 Días / 7 Noches',
    highlights: ['Trekking en la mítica isla Robinson Crusoe', 'Buceo en aguas endémicas cristalinas', 'Estadía combinada en Lodge Rincón de Navegantes', 'Lobos marinos de dos pelos'],
    description: 'La expedición insular por excelencia hacia uno de los ecosistemas con mayor endemismo del planeta.',
    mapImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir / Yate Terranova (+ Lodge)',
  },
  {
    id: 'ruta-selkirk',
    title: 'Ruta 4: Desafío Alejandro Selkirk (Más Afuera)',
    subtitle: 'Pacífico Sur Profundo — Isla Alejandro Selkirk',
    duration: '10 Días / 9 Noches',
    highlights: ['Navegación de altura extrema', 'Pesca de altura y avistamiento de cetáceos', 'Trekking en farellones de más de 1.000m', 'Santuario de flora endémica'],
    description: 'Expedición para exploradores apasionados hacia la isla más remota del archipiélago, con recalada en ensenadas vírgenes.',
    mapImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    recommendedVessel: 'Velero Vegvisir o Yate Terranova',
  },
];
